name: compile-gitbook
on:
  push:
    branches: [gitbook-setup]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gitbook
          path: gitbook
      - run: |
          mkdir -p gitbook/tikz-images
      - run: |
          sed -i -e 's/..\/..\/header.tex/main\/header.tex/g' main/**/Notes/notes.tex
      - uses: docker://pandoc/latex:2.11
        with:
          args: --standalone --to markdown --from latex+raw_tex --filter pandoc_filter.py --output=gitbook/ee128.md main/EE128/Notes/notes.tex
      - run: |
          mv tikz_images/* gitbook/tikz_images
      - run: |
          cd gitbook
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Recompile Markdown from LaTeX source"
          git push
