name: compile-gitbook
on:
  push:
    branches: [gitbook-setup]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gitbook
          path: gitbook
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip install pandocfilters
          sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - run: |
          mkdir -p gitbook/tikz-images
          sed -i -e 's/..\/..\/header.tex/main\/header.tex/g' main/**/Notes/notes.tex
          sed -i -e 's/compat=1.16/compat=1.15/g' main/imports.tex
      - uses: docker://pandoc/latex:2.11
        with:
          args: --standalone --to json --from latex+raw_tex --output=main/tmp.json main/EE128/Notes/notes.tex
      - run: |
          cd main
          chmod +x pandoc_filter.py
          cat tmp.json | ./pandoc_filter.py > filtered.json
          cd ../
      - uses: docker://pandoc/latex:2.11
        with:
          args: --standalone --to markdown --from json --output=gitbook/ee128.md main/filtered.json
      - run: |
          ls main/tikz-images
          cp -a main/tikz-images/. gitbook/tikz-images
      - run: |
          cd gitbook
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Recompile Markdown from LaTeX source"
          git push
