name: test-gitbook
on:
  pull_request:
    branches: master
    types: [opened, edited, synchronize, reopened]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout gitbook
        uses: actions/checkout@v2
        with:
          ref: gitbook
          path: gitbook
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip install pandocfilters
          pip install regex
          pip install pyyaml
          sudo apt-get install texlive-latex-recommended texlive-science texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
          sudo apt-get install ghostscript
      - name: Setup Environment
        run: |
          git -C main submodule init
          git -C main submodule update
          rm -rf gitbook/.gitbook/assets
          mkdir -p gitbook/.gitbook/assets
          sed -i -e 's/..\/..\/header.tex/main\/header.tex/g' main/**/Notes/notes.tex
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
      # Conversion Steps. Output a JSON file to the main folder
      - name: Convert EECS225A to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/eecs225a.json main/EECS225A/Notes/notes.tex
      - name: Convert EECS127 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/eecs127.json main/EECS127/Notes/notes.tex
      - name: Convert EECS126 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/eecs126.json main/EECS126/Notes/notes.tex
      - name: Convert EE128 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee128.json main/EE128/Notes/notes.tex
      - name: Convert EE123 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee123.json main/EE123/Notes/notes.tex
      - name: Convert EE120 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee120.json main/EE120/Notes/notes.tex
      - name: Convert EE222 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee222.json main/EE222/Notes/notes.tex
      # Filter Steps. Output a JSON file to the main folder
      - name: Filter 
        run: |
          cd main
          chmod +x pandoc_filter.py
          cat ee128.json | ./pandoc_filter.py > ee128-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat ee123.json | ./pandoc_filter.py > ee123-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat ee120.json | ./pandoc_filter.py > ee120-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat eecs126.json | ./pandoc_filter.py > eecs126-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat eecs127.json | ./pandoc_filter.py > eecs127-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat eecs225a.json | ./pandoc_filter.py > eecs225a-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cat ee222.json | ./pandoc_filter.py > ee222-filtered.json
          cp -a tikz-images/. ../gitbook/.gitbook/assets
          cd ../
      # Markdown conversion steps. Output a MD file to the output directory
      - name: Convert EECS126 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EECS126.md main/eecs126-filtered.json
      - name: Convert EECS127 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EECS127.md main/eecs127-filtered.json
      - name: Convert EE128 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EE128.md main/ee128-filtered.json
      - name: Convert EE123 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EE123.md main/ee123-filtered.json
      - name: Convert EE120 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EE120.md main/ee120-filtered.json
      - name: Convert EECS225A to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EECS225A.md main/eecs225a-filtered.json
      - name: Convert EE222 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables-smart --from json --atx-headers --output=gitbook/EE222.md main/ee222-filtered.json
      - name: Compile Book
        run: |
          mv main/create_book.py gitbook/create_book.py
          chmod +x gitbook/create_book.py
          cd gitbook
          python3 create_book.py EE120.md EE123.md EECS126.md EECS127.md EE128.md EECS225A.md EE222.md
          ls -la .gitbook/assets
          cd ../
          sed -i -e 's/\\\$\\\$/\$\$/g' gitbook/**/*.md
      - name: Upload Book
        uses: actions/upload-artifact@v2
        with:
          name: final-output
          path: gitbook
      - name: Generate Patch
        run: |
          cd gitbook
          git add .
          git diff --staged > gitbook.patch
      - name: Upload Patch
        uses: actions/upload-artifact@v2
        with:
          name: gitbook-patch
          path: gitbook/gitbook.patch

