name: compile-gitbook
on:
  push:
    branches: [gitbook-setup]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          ref: gitbook
          path: gitbook
      - run: |
          cp main/header.tex ../../header.tex
      - uses: docker://pandoc/latex:2.11
        with:
          args: --standalone --to markdown --from latex --output=gitbook/ee128.md main/EE128/Notes/notes.tex
      - run: |
          cd gitbook
          git pull
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Recompile Markdown from LaTeX source"
          git push
