name: compile-gitbook
on:
  push:
    branches: [gitbook-setup]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - run: |
          mkdir gitbook
      - uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown --from latex --output=gitbook/ee128.md main/EE128/Notes/notes.tex
      - uses: actions/checkout@v2
        with:
          ref: gitbook
          path: gitbook
      - run: |
          cd gitbook
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add gitbook
          git commit --amend --no-edit
          git push
