name: test-gitbook
on:
  pull_request:
    branches: master
    types: [opened, edited, synchronize, reopened]
jobs:
  compile-pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          path: main
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Python Setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Dependency Installation
        run: |
          python -m pip install --upgrade pip
          pip install pandocfilters
          pip install regex
          sudo apt-get install texlive-latex-recommended texlive-science texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      - name: Setup Environment
        run: |
          mkdir output
          mkdir -p output/.gitbook/assets
          sed -i -e 's/..\/..\/header.tex/main\/header.tex/g' main/**/Notes/notes.tex
          sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/g' /etc/ImageMagick-6/policy.xml
      - name: Convert EECS126 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/eecs126.json main/EECS126/Notes/notes.tex
      - name: Convert EE128 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee128.json main/EE128/Notes/notes.tex
      - name: Convert EE123 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee123.json main/EE123/Notes/notes.tex
      - name: Convert EE120 to JSON
        uses: docker://pandoc/latex:2.11
        with:
          args: --to json --from latex+raw_tex --output=main/ee120.json main/EE120/Notes/notes.tex
      - name: Filter 
        run: |
          cd main
          chmod +x pandoc_filter.py
          cat ee128.json | ./pandoc_filter.py > ee128-filtered.json
          cat ee123.json | ./pandoc_filter.py > ee123-filtered.json
          cat ee120.json | ./pandoc_filter.py > ee120-filtered.json
          cat eecs126.json | ./pandoc_filter.py > eecs126-filtered.json
          cd ../
      - name: Convert EECS126 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables --from json --atx-headers --output=output/EECS126.md main/eecs126-filtered.json
      - name: Convert EE128 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables --from json --atx-headers --output=output/EE128.md main/ee128-filtered.json
      - name: Convert EE123 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables --from json --atx-headers --output=output/EE123.md main/ee123-filtered.json
      - name: Convert EE120 to Markdown
        uses: docker://pandoc/latex:2.11
        with:
          args: --to markdown+pipe_tables-simple_tables --from json --atx-headers --output=output/EE120.md main/ee120-filtered.json
      - name: Copy Images
        run: |
          cp -a main/tikz-images/. output/.gitbook/assets
      - name: Save raw markdown
        uses: actions/upload-artifact@v2
        with:
          name: pandoc-output
          path: output
      - name: Compile Book
        run: |
          mv main/create_book.py output/create_book.py
          chmod +x output/create_book.py
          cd output
          python3 create_book.py EE120.md EE123.md EECS126.md EE128.md 
          cd ../
          sed -i -e 's/\\\$\\\$/\$\$/g' output/**/*.md
      - name: Upload Book
        uses: actions/upload-artifact@v2
        with:
          name: final-output
          path: output
